project:
  title: "nfi-web"
  output-dir: ./output
  type: website
website:
  title: NFI Urban Analytics 2024 - Part 1
  description: NFI Urban Analytics content - Part 1
  page-navigation: true
  repo-url: https://github.com/Norman-Foster-Institute/ua_2024
  navbar:
    search: true
  search:
    location: navbar
    type: overlay
  sidebar:
    tools:
      - icon: github
        href: https://github.com/Norman-Foster-Institute/ua_2024
    contents:
      - href: index.qmd
        text: Home
      - section: Setup
        contents:
          - chapter_0/index.qmd
          - chapter_0/installation.qmd
          - chapter_0/anaconda.qmd
      - section: Basic Coding
        contents:
          - chapter_1/python.ipynb
          - chapter_1/open_source.qmd
          - chapter_1/pandas.ipynb
      - section: GIS Tools
        contents:
          - chapter_2/gis.qmd
          - chapter_2/qgis.qmd
          - chapter_2/cloud.qmd
  page-footer:
    center:
      - text: "License"
        href: https://github.com/Norman-Foster-Institute/ua_2024/blob/main/LICENSE
format:
  html:
    theme: cosmo
    toc: true
