name: nfiua
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # to run the code
  - geopandas
  - osmnx
  - pandas
  - seaborn
  # infrastructure
  - nbformat
  - ipykernel
  - jupyter
  - jupyter-cache
  - jupyterlab
  - pip
