# Software & Accounts

## Github & Student Developer Pack

Instructions for how to setup your Github account and how to sign-up for the Github [Student Developer Pack](https://education.github.com/pack) will be given in class. Please don't try to activate the Student Developer Pack ahead of class. This is so that it can be configured with the correct accounts and procedure.

## CARTO Account

Setup for the CARTO account will be detailed in class after activating the Github Student Developer Pack.

## QGIS

Download and install QGIS form the official [download links](https://qgis.org/en/site/forusers/download.html).

## Anaconda

Download and install Anaconda from the official [download links](https://www.anaconda.com/download/).

## Table Plus

Download and install [TablePlus.](https://tableplus.com/). This is a tool for interacting with databases.

## Tableau

Download and install [Tableau Desktop](https://www.tableau.com/academic/students#form) using you **UAM** email address and credentials. This same credentials will serve you for **Tableau Prep** if you want to make use of it.
See [Intro to Tableau](../chapter_1/intro_to_tableau.qmd) for more.