---
title: "Bonus: Tableau"
date-format: long
date-modified: last-modified
lang: en
language: 
  title-block-modified: "Last update"
---

::: {.callout}
Make sure you have downloaded the software using the instructions in [Software & Accounts](../chapter_0/installation.qmd)
:::

Tableau is a leading data visualization tool that simplifies the process of converting complex data into interactive and visually appealing dashboards and reports. It is highly regarded in the business intelligence (BI) community for its ability to facilitate data-driven decision-making through an intuitive interface that accommodates users of all skill levels. By supporting a wide variety of data sources (including some spatial formats like _shapefiles_)) and enabling quick identification of data trends and patterns.

>With your student account you also have full access to **Tableau Prep**, a visual tool for data cleaning.

## Tableau Desktop Structure
```{mermaid}
flowchart LR
    subgraph Datasources
    A[(DB 1)]
    a[(DB 2)]
    end 

    subgraph Views
    B[Linechart]
    C[Map]
    D[Barchart]
    end

    subgraph Dashboards
    E{{Dashboard 1}}
    F{{Dashboard 2}}
    end 

    subgraph Stories
    S{Story}
    end 

    A --> B
    A --> C
    A --> D
    a --> D

    B --> E
    C --> E
    D --> F
    i(((images))) -.- E
    t(((texts))) -.- F 

    E --> S
    F --> S
    i -.- S
    t -.- S
```

## Data Sources: Connecting to data

In tableau you can connect simultaneously to multiple data sources (including Postgres) and/or individual _shapefiles_ and .CSV ('text files'). 

When you connect to more than one dataset you can establish three possible scenarios:

- **Create a `logical table`**: Tableau's lingo for the result from joining `physical` tables together
- **Create a relationship**: In this case your tables will not be joined if the specific chart you are building does not require to do so.
- **Create an independent data source**: In this case you limit the potential to use measures from multiple datasources.

Depending on your use case you might want to use different techniques. But note that only the fields that you bring into the view are considered for the construction of the queries (behind the scenes).

### Live vs Extract

Once the tables have been brought in and your initial filters have been set you can choose one of two options on how you are going to operate with the data in the next steps. 

- **Live** : when your establish just the relationships described above but the actual queries happen as you build your charts (and maps) are directed to your connections in each modification. Heavier on performance.
- **Extract** : when you create a resulting file (called Tableau extract) which is optimized to speed up performance and incoportates the resultiong joined tables and relatioships you have established. This is the reccomended approach. 

Note that Extracts can always be refreshed if your input data changes or you want to make adjustment to your joins / relations. 

:::{.callout-important}
### Datasets 

For this excercise we are going to use Spanish Census data at the 'census section' level (the lowest level of annonimised data). Both datasets come from the [INE](https://www.ine.es/) - National Institute of Statitics in Spanish. 

- **Population by gender and origin** in _.CSV_ format : [here](https://ine.es/buscar/searchResults.do?Menu_botonBuscador=&searchType=DEF_SEARCH&startat=0&L=0&searchString=poblacion%20seccion%20censal)
- **Census Sections** in _.SHP_ format : [here](https://www.ine.es/ss/Satellite?L=es_ES&c=Page&cid=1259952026632&p=1259952026632&pagename=ProductosYServicios/PYSLayout)
:::

## Views: Creating visualizations

This is where you are going to create all of your individual charts and graphs. Two important field types are automatically created (based on the data types) to help you set up your visualisations:

- **Dimensions** (blue): All qualitative and categorical fields in your dataset. eg. 'nationality', 'gender', etc...
- **Measures** (green): Continuous fields where you can apply `SUM`, `AVG`, `MIN`, `MAX` calculations. eg. 'population', 'age', etc..
  - Note that `geometries` are considered measures but deconstructed automatically into Longitude and Latitude when brought to the view. 

**To create new fields** right click next to your fields ans select `Create Calculated Field...`
> Tableau uses a SQL based syntax but to discover more see [documentation](https://help.tableau.com/current/pro/desktop/en-us/functions_operators.htm)

To build your charts **3 things** need careful attention:

- **MARKS CARD**: Establishes the type of graph you want to build. eg: lineschart, barchart, map, piechart. etc..
- **COLUMNS and ROWS** shelves: Determine what happend in your vertical and horizontal axis.
- **FILTERS CARD**: The place to customized what gets filtered for the current chart. 

::: {.callout-warning}
Be extra critical about the numbers!
Tableau is really good at generating outputs but the results should make sense to you and if possible, always try to sense check with other sources. 
:::

::: {.callout-important}
### Exercise
Drag and drop fields to create the following charts:

- **Map**: Displaying the total population per 'census section' in the 'Vasque Country' (`Pais Vasco`)
- **Bar graph**: Number of people per province splitted by `gender`.
- **Big Numbers**: Three big numbers: `Total Population`, `% Nacionals`, `% Foreigns`. 
  - These will serve us to sense check the values on our Dashboard
- **Others**: try to come up with new fields that could enrich the analysis. 
:::

## Dashboards (& Stories): Interacting and Enhancing views

In this step is where you put your pieces together. 
If the visualizations you have made share the same datasource, you can use the different views to **filter or highlight** parts of other views.

The recomendation is to create dashboards with no more than 3 or 4 components (views, text blocks, images). When trying to tell a story with data you want to eliminate all possible distractions.

:::{.callout-tip}
Visual guide to selecting the right type of chart.
The Financial Times Visual Vocabulary:

 - [Web version](https://ft-interactive.github.io/visual-vocabulary/)
 - [Poster version(s)](https://github.com/Financial-Times/chart-doctor/tree/main/visual-vocabulary) in multiple languages.
 - [Tableau Public](https://public.tableau.com/app/profile/andy.kriebel/viz/VisualVocabulary/VisualVocabulary)

:::

## Sharing and Publishing

Dashboards, Stories and Views can be exported as images (PDF, JPEG, etc..), as PowerPoint presentations but you can Publish your results to Tableau Public - a free and open server where dashboards remain interactive. 

Like other softwares you can share your work as Tableau workbook packaged (.twbx), which contains all the data, or as a visualization tool only (.twb) if you know that the other person will have access to the same data connections you used. 

## Resources for Further Learning

- [Tableau Public](https://public.tableau.com/app/discover)
- [Official videos](https://www.tableau.com/learn/training)
- [VizWiz](https://www.vizwiz.com/) one of the best teaching resouces out there. #MakeOverMondays are great excercises.
