# Open Source

Use open-source code wherever possible! Open source code consists of a dynamic ecosystem of constantly co-evolving code packages. This collaborative development has permitted a remarkable progression in the capabilities and sophistication of freely accessible code. This has benefitted geospatial and urban analysis immensely, making these tools more widely accessible to those who wish to use them.

To further cement some basic Python skills, we'll be making use of the open-source [learn-python3](https://github.com/jerry-git/learn-python3) repository, created and maintained by Github user `jerry-git`.

::: {.callout-tip}
We will be using open-source packages extensively throughout this course. To show your appreciation for online open-source code, please click the "Star" button in the respective Github repositories! If the repository provides a citation or publication reference, please be sure to cite these clearly in any derivative work. If you continue to develop your Python skills you may one day be able to become an active contributor to the ongoing development of open-source projects.
:::

## Fetching the notebooks

- Go to the [learn-python3](https://github.com/jerry-git/learn-python3) repository.
- Before using code from online code repositories, double-check the license type. In this case, it is MIT licensed which is an open-source license.
- Download the repository to a local folder by clicking on the green "code" dropdown button, and select "Download ZIP".
- Unzip if necessary and move the folder to a working location of your choosing.

## Using the notebooks
- Open your Anaconda Navigator and launch Jupyter Lab as previously.
- Once Jupyter Lab has launched, navigate to the downloaded folder and open the `notebooks` > `beginner` > `notebooks` folder.
- Sequentially work through notebooks from `1` to `7`. Feel free to experiment with the notebook content.
- Emerging AI tools such as ChatGPT are incredibly useful for understanding and adapting code. These tools are largely replacing previously used online resources such as [Stack Overflow](https://stackoverflow.com) (though these can still be useful).