# Intro to QGIS

## QGIS UI

We'll first explore the QGIS user interface, taking some time to explore:

- **Main Interface**: The map area, toolbars, layers panel, status bar, dock panels.
- **Toolbars**: These are collections of icons and tools that provide quick access to commonly used features and functions in QGIS. These can be customised based on your preferences. Some of the common toolbars provide functionality such as zooming, panning, selecting features, and editing features.
- **Map View**: This is the central area where your maps and layers are displayed. We'll explore how to navigate the map view, including zooming, panning, and identifying features.
- **Browser Panel**: For browsing and loading data from your file system, databases, and web services.
- **Layers Panel**: Here, you can see a list of all the layers loaded in your project. Layers can be organised, styled, and otherwise configured.
- **Attribute Table**: This panel lets you view and edit the attribute data associated with your vector layers.
- **Status Bar**: Located at the bottom, the status bar shows information about the map and your project, such as the current map scale, the coordinate reference system, and messaging about ongoing processes.
- **Plugins**: QGIS can be extended with plugins. We'll briefly touch on how to find, install, and use plugins to enhance the functionality of QGIS.

## Plugins

Install the Quick Map Services (QMS) Plugin:

- From the `Plugins` menu, select `Manage and Install Plugins`
- Search for `QMS`
- Install `QuickMapServices`
- `Install` and `Close` the window.

This plugin will add a new menu entry under the `Web` menu.

- From the `Web` menu, select `QuickMapServices`, then `OSM` and `OSM Standard`.
- This will add a map to your map view.

## XYZ Tiles

XYZ tiles are a popular way to represent map tile data in a simple and standardized format, allowing for efficient storage, retrieval, and display of map imagery at various scales. The "XYZ" refers to the coordinate system used to locate the tiles. "X" and "Y" represent the tile's column and row, respectively, in a grid layout, with the origin typically at the top-left corner of the map. The "Z" parameter stands for zoom level, where higher zoom levels correspond to more detailed views (i.e., a higher resolution). This system enables GIS applications to quickly load the appropriate level of detail for a given view, making it a cornerstone of web mapping services like Google Maps and OpenStreetMap. It allows for seamless and efficient navigation across various scales and locations on a digital map.

To establish a new connection:

- On the Browser panel, right-click on `XYZ Tiles` -> `New Connection...`
- Asign a name to the connection (eg. _OpenStreetMap_)
- Paste the respective `URL`

Depending on the connection, some of other connection attributes might be required (eg. Authentication details)

> We reccomend you establish at least the following connections:
> - **OpenStreetMap** : https://tile.openstreetmap.org/{z}/{x}/{y}.png
> - **Google Imagery Hybrid** : http://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}&s=Ga

::: {.callout-tip}
Useful list of many others Tiles. 
[https://qms.nextgis.com](https://tile.openstreetmap.org/{z}/{x}/{y}.png)
Note, make sure you navigate to the TMS section and the reported status = `works` (symbolised with the green dot).
:::

## Datasets

- Download the municipal neighbourhoods as a SHP file: [Barrios municipales de Madrid](https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=760e5eb0d73a7710VgnVCM2000001f4a900aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default)

- Download the population by district and neighbourhood dataset as a CSV file: [Población por distrito y barrio a 1 de enero](https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=0cccaebc07c1f710VgnVCM2000001f4a900aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default)


## Coordinate Reference Systems

Geospatial data is represented using a coordinate reference system (CRS). QGIS will ordinarily detect this information automatically. However, it can display information in any selected CRS, so you can open multiple files in different CRSs and these will display correctly. This is because QGIS will reproject each respective file into the map's currently selected CRS system.

In the lower right corner of the status bar at the bottom of the screen:

- Select the CRS button to open the project's CRS configuration.
- Search for CRS code `3857`, then select it, `Apply`, and `OK`.

> Hint: When using OSM base maps, the base maps will render more performantly in the Web Mercator projection (`3857`). This is because QGIS then doesn't need to dynamically reproject the map tiles out of their native `3857` projection.

## Loading Data

Load your first dataset by dragging and dropping the shapefile (the downloaded file ending with `.shp`) into your map view.

- You can toggle layer visibility and order using the Layers Panel.
- Use the `Select Features` button to select a feature and see it highlighted.
- Click the `Pan Map to Selection` button to see the map zoom to the currently selected feature
- Click the `Zoom Full` button to return to a view of the full dataset.
- Use the `Identify Features` button to see attribute information for a particular feature.
- Click the `Toggle Editing` button -> this will let you delete existing features or add new features - use with caution! Don't make any changes for now, just click the `Toggle Editing` button again to exit edit mode.

## Saving and exporting data

We don't want to edit the original dataset, so let's make a copy and work with that instead:

- Right click the layer in the Layer Panel and select `export` -> `Save Features as`
- Select the `GeoPackage` format.
- Select a file location on disk and give it a distinctive name such as `my_gpkg`.
- Select `3035` for the CRS projection
- Check that `Add saved file to map` at the bottom of the window is selected
- Select `OK`
- The file will be saved and will automatically load into your map.
- Remove the original `SHP` file from your Layers Panel since it is no longer needed. This can be done with the `Remove Layer` button.

## Attributes

Attributes in GIS layers provide additional information about the spatial features in the data. They include text, numbers, dates, or images. Attributes help add context to the geographic elements, enabling better analysis and visualization. They can be used to filter, classify, and symbolize features based on their characteristics. Attributes play a crucial role in data analysis, allowing us to gain insights, make comparisons, and create meaningful visual representations.

Using the Municipal Boundaries `my_gpkg` dataset:

- Open the attribute table for the neighbourhood boundaries by right clicking on the layer in the Layers Panel and selecting `Attribute Table`. From the Attribute table you can try the same steps you tried for the map view (selecting, zooming to, editing).
- Toggle Editing Mode by pressing the `Toggle Editing Mode` button.
- Click on the `New Field` button in the toolbar
- Set the Name as `area` and the type as `Decimal number`, then `OK`.
- Check that no rows are selected (otherwise the calculation only applies to the selected rows).
- Open the Field Calculator by clicking its icon (abacus symbol) in the toolbar.
- Select `Update existing field` and select the `area` column.
- In the `Expression` pane, enter `$area`, then press the blue forward button below to preview the results of the calculation.
- Press `OK` and check that your area column has been updated.
- Press the `Save edits` button to save your calculation.
- Turn off editing mode.

We'll now add another column, this time we'll use another column as input and we will transform the data from a text to an integer.

- Turn editing mode on
- Open the Field Calculator
- This time select `Create a new field` and call it `cod_barrio`
- Check that it is an `Integer` type
- In the expression, enter `to_int(COD_BAR)` -> this will take the text from the `COD_BAR` column and will cast this to an integer. In the process, the data will drop the leading zero.
- Apply the change, save to disk, and toggle editing to off.

## Loading CSV files

- To load the CSV file we'll go to the `Layer` menu bar, `Add Layer`, then `Add Delimited Text Layer`.
- For `File name`, navigate to your CSV file
- This file uses semi-colon delimeters, so select `Custom delimiters` and check that `Semicolon` is selected
- Check that the option for `First record has field names` is selected. This will automatically use the first line of the CSV to set the attribute names.
- Select `No geometry`. This will load the dataset without visual geometric information. Note that if you have longitude and latitude information in CSV columns (or Eastings and Northings for projected CRS), then you can specify these columns and QGIS will generate the point geometries accordingly.
- Select `Add` then `Close`.
- Note that this layer looks different in the Layers Panel because it doesn't have associated geometry. However, you can still view the Attribute Table.
- Right click on the layer and select `export` -> `Save Features as`. Then save the layer as a new CSV file called `my_csv`. As before, select the option to add the layer to the map, save, then remove the original input CSV from the Layers Panel.

## Selecting and deleting features

- Open the attribute table for the `my_csv` layer by right clicking on the data table in the Layers Panel and selecting `Attribute Table`.
- Order the data by clicking the `fecha` column header, order in descending order by clicking again.
- Click on the first entry then hold down shift and click on the last entry with a `fecha` value of `1 de enero de 2023`
- Click the `Invert selection` button.
- Toggle editing.
- Click the `Delete selected features` button.
- Save and turn off editing.

## Joins

- Open the Attribute Panels for both the `my_gpkg` and the `my_csv` layers.
- We want to "Join" information from the CSV dataset to the neighbourhood boundaries using the matching identifiers in the respective `cod_barrio` / `cod_barrio` columns.
- Close the Attribute Panels.
- Double click on the `my_gpkg` layer to open the properties panel.
- Click `Joins` in the left sidebar.
- Click the plus button to create a new join.
- Select the `my_csv` table for the `Join layer` -> the layer from which attributes will be joined to `my_gpkg`.
- Select the `cod_barrio` column for the `Join field`
- Select the `cod_barrio` column for the `Target field`
- Click `OK` and close the layer properties.
- Reopen the Attribute Panel for the `my_gpkg` dataset, you'll see extra columns which have now joined the data from the `my_csv` table into their corresponding boundaries based on the matching identifiers.
- Let's export this to a new file to `my_joined_gpkg`, which will now include the joined data.
- Remove `my_csv` and `my_gpkg` from the Layers Panel.

## Visualisation

- Open the `my_joined_gpkg` layer properties by double clicking on the layer name in the Layers Panel.
- Select `Labels` in the left pane, select `Single Labels`, then select the `BARRIO_MT` column, then apply. This will add the Barrio names to the map. You can format labels to your heart's content.
- Select `Symbology` in the left pane. In class, we will walk through a variety of options for map styling. There are almost limitless options so feel free to be creative.

## Connecting to DB

::: {.callout-tip}
Connection details will be provided during class. Note that all connections to the database are IP protected.
:::

## Mapping Vector Data

For this excercise we are going to use the historic center of San Marino. The idea is to familiarize yourself with inputing geometry, first. Attributes will be added at later stages.
Each scholar, must produce two individual GeoPackage Layers (locally): 

- **Buildings layer**: (Polygons, `CRS: 3035`) representing all the buildings within the tiles assigned.
    - suggested name : *buildings_[scholarname]*
- **Street Network layer**: (Linestring, `CRS: 3035`) representing the pedestrian routes through the tiles assigned. 
    - suggested name : *network_[scholarname]*

Each scholar has been assigned with different areas of the republic that can be found in the following path of `nfi` database:
 - `nfi.sanmarino.base_mapping`

 Explore the attributes `buildings` and `street_network` to see your areas and collaborate with the neighbour tiles.

::: {.callout-tip}
Make sure you activate the `Snapping Toolbar` by right-clicking on any empty space of the toolbar. 
Explore different pixel tolerance values as well as options like the `Topological Editing` and the `Intersection Snapping`.
:::

### Optional 
If you're feeling like doing the extra mile, you can start combining the tiles from your adjacent neighbours and/or adding attributes to your current layers.

When merging files, one must make sure that all the Linestrings (from the Network layer) and Polygon edges are approprietly snappped.

## Resources

There is a lot that can be done with QGIS and we have just skimmed the surface!

The [QGIS Tutorials and Tips](https://www.qgistutorials.com/en/index.html) is a great resource for QGIS.

For lab-work, please do the following tutorials from [QGIS Tutorials and Tips](https://www.qgistutorials.com/en/docs/introduction.html) in your own time to build some general familiarity with QGIS:

- [Making a Map](https://www.qgistutorials.com/en/docs/3/making_a_map.html)
- [Basic Vector Styling](https://www.qgistutorials.com/en/docs/3/basic_vector_styling.html)
- [Digitizing Map Data](https://www.qgistutorials.com/en/docs/3/digitizing_basics.html)
- [Working with Projections](https://www.qgistutorials.com/en/docs/3/working_with_projections.html)
- [Creating Heatmaps](https://www.qgistutorials.com/en/docs/3/creating_heatmaps.html)
